services:
  app: # PHP-FPM

    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./src:/var/www/html:rw
    networks:
      - backend
  nginx:
    image: nginx:1.25.0-alpine #nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - ./docker/nginx/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - app
    networks:
      - backend

  mysql:
    image: mysql:8.0.36 #mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE:    ${DB_DATABASE}
      MYSQL_USER:        ${DB_USERNAME}
      MYSQL_PASSWORD:    ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
  redis:
    image: redis:7.0-alpine #redis:7-alpine
    restart: unless-stopped
    networks:
      - backend
    # Optional: expose to host if you need to connect from outside Docker
    ports:
      - "6379:6379"

# persist MySQL data
volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
